version: '3.8'

services:
  web:
    build: ./docker_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docker_django/:/usr/src/docker_django/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
